'use client';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { Network, Search, Zap } from 'lucide-react';

export default function KnowledgeGraphPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <nav className="glass sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 bg-blue-600 rounded-lg shadow-md flex items-center justify-center text-white font-bold">N</div>
              <span className="text-2xl font-bold text-gray-900 tracking-tight">NexusAI</span>
            </div>
            <div className="hidden sm:flex sm:space-x-8 items-center">
              <Link href="/dashboard" className="border-transparent text-gray-500 hover:text-gray-700 px-1 pt-1 border-b-2 text-sm font-medium">Dashboard</Link>
              <Link href="/knowledge-graph" className="border-blue-600 text-blue-600 px-1 pt-1 border-b-2 text-sm font-medium">Knowledge Graph</Link>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <motion.header 
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-10 text-center"
        >
          <div className="inline-flex items-center justify-center p-4 bg-blue-100 rounded-full mb-4">
            <Network className="w-12 h-12 text-blue-600" />
          </div>
          <h1 className="text-5xl font-extrabold text-blue-900 tracking-tight">Family Brain Network</h1>
          <p className="mt-4 text-lg text-blue-700 max-w-2xl mx-auto">Explore interconnected entities and insights generated by the AI.</p>
        </motion.header>

        <div className="glass rounded-2xl h-96 flex items-center justify-center bg-slate-900 text-white relative overflow-hidden">
          <div className="absolute inset-0 opacity-20 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>
          <p className="z-10 font-medium">Interactive Graph Visualization Active</p>
        </div>
      </main>
    </div>
  );
}
